-- liquibase formatted sql

-- changeset thanhch:1711610616245-1
INSERT INTO "flyway_schema_history" ("installed_rank", "version", "description", "type", "script", "checksum", "installed_by", "installed_on", "execution_time", "success") VALUES (1, '1', '<< Flyway Baseline >>', 'BASELINE', '<< Flyway Baseline >>', NULL, 'thanhch', '2023-04-26 22:50:41.951482', 0, TRUE);

-- changeset thanhch:1711610616245-2
INSERT INTO "comments" ("comment_id", "content", "post_id", "created_at", "created_by", "updated_at", "updated_by") VALUES (1, '1st comment', 1, '2023-02-01 20:46:01.35', 1, '2023-02-01 20:46:01.35', 1);
INSERT INTO "comments" ("comment_id", "content", "post_id", "created_at", "created_by", "updated_at", "updated_by") VALUES (2, '2st comment', 2, '2023-02-02 20:46:01.35', 1, '2023-02-02 20:46:01.35', 1);
INSERT INTO "comments" ("comment_id", "content", "post_id", "created_at", "created_by", "updated_at", "updated_by") VALUES (3, '3st comment', 1, '2023-02-03 00:46:01.35', 1, '2023-02-03 00:46:01.35', 1);
INSERT INTO "comments" ("comment_id", "content", "post_id", "created_at", "created_by", "updated_at", "updated_by") VALUES (4, '4st comment', 1, '2023-02-04 01:00:01.35', 2, '2023-02-04 01:00:01.35', 2);

-- changeset thanhch:1711610616245-3
INSERT INTO "posts" ("post_id", "title", "content", "created_at", "created_by", "updated_at", "updated_by") VALUES (1, 'title', 'CONTENT', '2023-02-01 03:46:01.35', 1, '2023-02-01 03:46:01.35', 1);

-- changeset thanhch:1711610616245-4
INSERT INTO "users" ("user_id", "user_name", "password", "email", "role", "avatar", "active", "last_login", "created_at", "created_by", "updated_at", "updated_by") VALUES (1, 'thanhch', '123456', NULL, 'ADMIN', NULL, TRUE, NULL, '2024-02-07 09:49:14.008407', NULL, '2024-02-07 09:49:14.008407', NULL);

-- liquibase formatted sql

-- changeset thanhch:1711610696587-1
CREATE TABLE "flyway_schema_history" ("installed_rank" INTEGER NOT NULL, "version" VARCHAR(50), "description" VARCHAR(200) NOT NULL, "type" VARCHAR(20) NOT NULL, "script" VARCHAR(1000) NOT NULL, "checksum" INTEGER, "installed_by" VARCHAR(100) NOT NULL, "installed_on" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "execution_time" INTEGER NOT NULL, "success" BOOLEAN NOT NULL, CONSTRAINT "flyway_schema_history_pk" PRIMARY KEY ("installed_rank"));

-- changeset thanhch:1711610696587-2
CREATE SEQUENCE  IF NOT EXISTS "comment_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset thanhch:1711610696587-3
CREATE TABLE "comments" ("comment_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "content" TEXT, "post_id" INTEGER, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "created_by" INTEGER, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER, CONSTRAINT "comments_pkey" PRIMARY KEY ("comment_id"));

-- changeset thanhch:1711610696587-4
CREATE SEQUENCE  IF NOT EXISTS "post_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset thanhch:1711610696587-5
CREATE TABLE "posts" ("post_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "title" VARCHAR(60), "content" TEXT, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "created_by" INTEGER, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER, CONSTRAINT "posts_pkey" PRIMARY KEY ("post_id"));

-- changeset thanhch:1711610696587-6
CREATE SEQUENCE  IF NOT EXISTS "user_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset thanhch:1711610696587-7
CREATE SEQUENCE  IF NOT EXISTS "tag_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset thanhch:1711610696587-8
CREATE TABLE "tags" ("tag_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "tag_name" TEXT, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "created_by" INTEGER, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER, CONSTRAINT "tags_pkey" PRIMARY KEY ("tag_id"));

-- changeset thanhch:1711610696587-9
CREATE TABLE "post_tags" ("tag_id" INTEGER, "post_id" INTEGER, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "created_by" INTEGER, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER);

-- changeset thanhch:1711610696587-10
CREATE TABLE "categories" ("category_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" TEXT, "parent_id" INTEGER, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "created_by" INTEGER, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER, CONSTRAINT "categories_pkey" PRIMARY KEY ("category_id"));

-- changeset thanhch:1711610696587-11
CREATE SEQUENCE  IF NOT EXISTS "category_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset thanhch:1711610696587-12
CREATE TABLE "post_categories" ("category_id" INTEGER, "post_id" INTEGER, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "created_by" INTEGER, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER);

-- changeset thanhch:1711610696587-13
CREATE INDEX "flyway_schema_history_s_idx" ON "flyway_schema_history"("success");

-- changeset thanhch:1711610696587-14
ALTER TABLE "tags" ADD CONSTRAINT "tags_tag_name_key" UNIQUE ("tag_name");

-- changeset thanhch:1711610696587-15
ALTER TABLE "post_tags" ADD CONSTRAINT "post_tags_tag_id_post_id_key" UNIQUE ("tag_id", "post_id");

-- changeset thanhch:1711610696587-16
ALTER TABLE "categories" ADD CONSTRAINT "categories_name_key" UNIQUE ("name");

-- changeset thanhch:1711610696587-17
ALTER TABLE "post_categories" ADD CONSTRAINT "post_categories_category_id_post_id_key" UNIQUE ("category_id", "post_id");

-- changeset thanhch:1711610696587-18
CREATE SEQUENCE  IF NOT EXISTS "hibernate_sequence" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset thanhch:1711610696587-19
CREATE TABLE "users" ("user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_name" VARCHAR(50), "password" VARCHAR(50), "email" VARCHAR(50), "role" ROLE DEFAULT 'USER', "avatar" TEXT, "active" BOOLEAN DEFAULT FALSE, "last_login" TIMESTAMP WITHOUT TIME ZONE, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "created_by" INTEGER, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER, CONSTRAINT "users_pkey" PRIMARY KEY ("user_id"));

-- changeset thanhch:1711610696587-20
ALTER TABLE "users" ADD CONSTRAINT "email_unique" UNIQUE ("email");

-- changeset thanhch:1711610696587-21
ALTER TABLE "users" ADD CONSTRAINT "username_unique" UNIQUE ("user_name");

-- changeset thanhch:1711610696587-22
DROP TABLE "test_table";

