-- liquibase formatted sql

-- changeset thanhch:1711631546105-1
CREATE TABLE "comments" ("comment_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "content" TEXT, "post_id" INTEGER, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "created_by" INTEGER, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER, CONSTRAINT "comments_pkey" PRIMARY KEY ("comment_id"));

-- changeset thanhch:1711631546105-2
INSERT INTO "comments" ("comment_id", "content", "post_id", "created_at", "created_by", "updated_at", "updated_by") VALUES (1, '1st comment', 1, '2023-02-01 20:46:01.35', 1, '2023-02-01 20:46:01.35', 1);
INSERT INTO "comments" ("comment_id", "content", "post_id", "created_at", "created_by", "updated_at", "updated_by") VALUES (2, '2st comment', 2, '2023-02-02 20:46:01.35', 1, '2023-02-02 20:46:01.35', 1);
INSERT INTO "comments" ("comment_id", "content", "post_id", "created_at", "created_by", "updated_at", "updated_by") VALUES (3, '3st comment', 1, '2023-02-03 00:46:01.35', 1, '2023-02-03 00:46:01.35', 1);
INSERT INTO "comments" ("comment_id", "content", "post_id", "created_at", "created_by", "updated_at", "updated_by") VALUES (4, '4st comment', 1, '2023-02-04 01:00:01.35', 2, '2023-02-04 01:00:01.35', 2);

-- changeset thanhch:1711631546105-3
CREATE TABLE "posts" ("post_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "title" VARCHAR(60), "content" TEXT, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "created_by" INTEGER, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER, CONSTRAINT "posts_pkey" PRIMARY KEY ("post_id"));

-- changeset thanhch:1711631546105-4
INSERT INTO "posts" ("post_id", "title", "content", "created_at", "created_by", "updated_at", "updated_by") VALUES (1, 'title', 'CONTENT', '2023-02-01 03:46:01.35', 1, '2023-02-01 03:46:01.35', 1);

-- changeset thanhch:1711631546105-5
CREATE TABLE "tags" ("tag_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "tag_name" TEXT, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "created_by" INTEGER, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER, CONSTRAINT "tags_pkey" PRIMARY KEY ("tag_id"));

-- changeset thanhch:1711631546105-6
CREATE TABLE "post_tags" ("tag_id" INTEGER, "post_id" INTEGER, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "created_by" INTEGER, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER);

-- changeset thanhch:1711631546105-7
CREATE TABLE "categories" ("category_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" TEXT, "parent_id" INTEGER, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "created_by" INTEGER, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER, CONSTRAINT "categories_pkey" PRIMARY KEY ("category_id"));

-- changeset thanhch:1711631546105-8
CREATE TABLE "post_categories" ("category_id" INTEGER, "post_id" INTEGER, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "created_by" INTEGER, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER);

-- changeset thanhch:1711631546105-9
ALTER TABLE "tags" ADD CONSTRAINT "tags_tag_name_key" UNIQUE ("tag_name");

-- changeset thanhch:1711631546105-10
ALTER TABLE "post_tags" ADD CONSTRAINT "post_tags_tag_id_post_id_key" UNIQUE ("tag_id", "post_id");

-- changeset thanhch:1711631546105-11
ALTER TABLE "categories" ADD CONSTRAINT "categories_name_key" UNIQUE ("name");

-- changeset thanhch:1711631546105-12
ALTER TABLE "post_categories" ADD CONSTRAINT "post_categories_category_id_post_id_key" UNIQUE ("category_id", "post_id");

-- changeset thanhch:1711631546105-13
CREATE TABLE "test-data" ("id" BIGINT);

-- changeset thanhch:1711631546105-14
CREATE TABLE "test-table" ("name" CHAR(1));

-- changeset thanhch:1711631546105-15
CREATE TABLE "users" ("user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_name" VARCHAR(50), "password" VARCHAR(50), "email" VARCHAR(50), "role" ROLE DEFAULT 'USER', "avatar" TEXT, "active" BOOLEAN DEFAULT FALSE, "last_login" TIMESTAMP WITHOUT TIME ZONE, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "created_by" INTEGER, "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER, CONSTRAINT "users_pkey" PRIMARY KEY ("user_id"));

-- changeset thanhch:1711631546105-16
INSERT INTO "users" ("user_id", "user_name", "password", "email", "role", "avatar", "active", "last_login", "created_at", "created_by", "updated_at", "updated_by") VALUES (1, 'thanhch', '123456', NULL, 'ADMIN', NULL, TRUE, NULL, '2024-02-07 09:49:14.008407', NULL, '2024-02-07 09:49:14.008407', NULL);

-- changeset thanhch:1711631546105-17
ALTER TABLE "users" ADD CONSTRAINT "email_unique" UNIQUE ("email");

-- changeset thanhch:1711631546105-18
ALTER TABLE "users" ADD CONSTRAINT "username_unique" UNIQUE ("user_name");

-- liquibase formatted sql

-- changeset thanhch:1711631614903-16
ALTER TABLE "posts" ADD "title" VARCHAR(60);

-- changeset thanhch:1711631614903-1
ALTER TABLE "categories" ALTER COLUMN  "created_at" SET DEFAULT NOW();

-- changeset thanhch:1711631614903-2
ALTER TABLE "comments" ALTER COLUMN  "created_at" SET DEFAULT NOW();

-- changeset thanhch:1711631614903-3
ALTER TABLE "post_categories" ALTER COLUMN  "created_at" SET DEFAULT NOW();

-- changeset thanhch:1711631614903-4
ALTER TABLE "post_tags" ALTER COLUMN  "created_at" SET DEFAULT NOW();

-- changeset thanhch:1711631614903-5
ALTER TABLE "posts" ALTER COLUMN  "created_at" SET DEFAULT NOW();

-- changeset thanhch:1711631614903-6
ALTER TABLE "tags" ALTER COLUMN  "created_at" SET DEFAULT NOW();

-- changeset thanhch:1711631614903-7
ALTER TABLE "users" ALTER COLUMN  "created_at" SET DEFAULT NOW();

-- changeset thanhch:1711631614903-8
ALTER TABLE "test-table" ALTER COLUMN "name" TYPE CHAR(1) USING ("name"::CHAR(1));

-- changeset thanhch:1711631614903-9
ALTER TABLE "categories" ALTER COLUMN  "updated_at" SET DEFAULT NOW();

-- changeset thanhch:1711631614903-10
ALTER TABLE "comments" ALTER COLUMN  "updated_at" SET DEFAULT NOW();

-- changeset thanhch:1711631614903-11
ALTER TABLE "post_categories" ALTER COLUMN  "updated_at" SET DEFAULT NOW();

-- changeset thanhch:1711631614903-12
ALTER TABLE "post_tags" ALTER COLUMN  "updated_at" SET DEFAULT NOW();

-- changeset thanhch:1711631614903-13
ALTER TABLE "posts" ALTER COLUMN  "updated_at" SET DEFAULT NOW();

-- changeset thanhch:1711631614903-14
ALTER TABLE "tags" ALTER COLUMN  "updated_at" SET DEFAULT NOW();

-- changeset thanhch:1711631614903-15
ALTER TABLE "users" ALTER COLUMN  "updated_at" SET DEFAULT NOW();

